### ISSUE TITLE
Does not work with NetBeans module development

### ISSUE THREAD

**Issue by gidash** [jonathanlermitage/tikione-jacocoverage#10]
1 Installed Java7u21, NetBeans 7.3.1
2 Created a simple NetBeans Platform Module, with simply one class, and one simple test with Junit4
3 Launched the action Test with JaCoCoverage gives this result:

Ant Test or JaCoCo Agent failed, JaCoCoverage can't process data.
(AntExitCode=0, JaCoCoBinReportFound=false)

Otherwise with a java project it works correctly

![jacocoverage issue](https://f.cloud.github.com/assets/4748487/686604/12a92dee-da5f-11e2-8abd-83ada7ddcd5a.jpg)

**Comment by jonathanlermitage** [comment]
A very very very big thank to Graeme Ingleby who provided a patch for NetBeans Module support.
Closing this issue. Expect a release (v1.5.0) tomorrow on GitHub and NetBeans Plugins Platform.
