### ISSUE TITLE
Ability to select testsuites to test

### ISSUE THREAD

**Issue by Dennis123789** [jonathanlermitage/tikione-jacocoverage#19]
Hi, I haven't been able to find a way to test testsuites, only tests. I have several suites with multiple tests, however in the suite there's code in the _setUpClass()_ which isn't excecuted when only testing the tests themselves. It's just an idea :) Thanks in advance!

**Comment by jonathanlermitage** [comment]
Sorry, the project is now over. Feel free to start a fork.
