### ISSUE TITLE
Ant Task or JaCoCo Agent failed for project with non US-ASCII path

### ISSUE THREAD

**Issue by kolgenpav** [jonathanlermitage/tikione-jacocoverage#28]
Windows 8.1, JDK 1.8.0_20, NetBeans 8.0.2, TikiOne JaCoCoverage plugin version 1.5.1.20150301.1800.
For ANT project with non US-ASCII characters in the path the "Run with JaCoCoverage" and "Test with JaCoCoveragge" commands results in an error: 
"Ant Task or JaCoCo Agent failed, JaCoCoverage can't process data. (AntExitCode=0, JacocoBinReportFound=false)"

**Comment by jonathanlermitage** [comment]
Hi,
could you show your path?

**Comment by kolgenpav** [comment]
The project path is c:\users\kgp\edu\ЯПЗТ\JUnitApp. The problen is in ЯПЗТ. 
I found that for projects with non US-ASCII characters in the path in Linux plugin works fine.
Most likely the problem is due to Windows uses non "UTF-8" encoding.

**Comment by jonathanlermitage** [comment]
Thx.
I'll try some options to make it work with the JaCoCo java-agent. If it fails, I'll add an option to customize the path of JaCoCo agent jar file.
I'll do that asap.

**Comment by jonathanlermitage** [comment]
Fixed!
You can now select the path of a custom javaagent.jar path (with ASCII characters only, to make it work).
Releasing 1.5.2 today.
