### ISSUE TITLE
Non termination with RCP modules

### ISSUE THREAD

**Issue by EnricoScantamburlo** [jonathanlermitage/tikione-jacocoverage#29]
I have tried this plugin on a module that is part of our NetBeans Based application. It launches the tests but after that it  does not seem to stop and starts generating huge (> Gb) files on my disk without stopping. I had to closet NetBeans to manually to stop it

**Comment by jonathanlermitage** [comment]
Hi,
the plugin has been tested on NetBeans modules only, not RCP apps.
Do you see interesting things in NetBeans logs?

**Comment by EnricoScantamburlo** [comment]
No, nothing on the IDE logs.
