### ISSUE TITLE
Plugin doesn't work when jacoco plugin version is not specified in maven pom.xml

### ISSUE THREAD

**Issue by TeofilisMartisius** [jonathanlermitage/tikione-jacocoverage#30]
Hi,

This plugin doesn't work if jacoco plugin version is not specified and left to maven to resolve. Maven will work fine and produce jacoco report, but netbeans integration will fail.

It starts working if you specify version explicitly.

For example:

    <build>
        <plugins>
            <plugin>
                <groupId>org.jacoco</groupId>
                <artifactId>jacoco-maven-plugin</artifactId>
                
                <executions>
                    <execution>
                        <goals>
                            <goal>prepare-agent</goal>
                        </goals>
                    </execution>
                    <execution>
                        <id>report</id>
                        <phase>prepare-package</phase>
                        <goals>
                            <goal>report</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

**Comment by jonathanlermitage** [comment]
Hi,
this plugins works with __Ant__ projects only, not Maven.
Maven support is already handled by NetBeans as described here: http://wiki.netbeans.org/MavenCodeCoverage

Regards,
