### ISSUE TITLE
Where is total Code Coverage ?

### ISSUE THREAD

**Issue by partho-maple** [jonathanlermitage/tikione-jacocoverage#31]
I am using this plugins on my Netbeans and run the test. But there is only code coverage for separate classes. Where can i find the total code coverage of a Java project ? Please suggest.

![screenshot_19](https://cloud.githubusercontent.com/assets/1577598/9043031/6a686c16-3a34-11e5-9950-092c8e743e89.jpg)

**Comment by jonathanlermitage** [comment]
The plugin reports are generated by the JaCoCo library.
Maybe there's an option to show global coverage. You could ask question to http://www.eclemma.org/jacoco/ ;)
