### ISSUE TITLE
Can't change color theme 

### ISSUE THREAD

**Issue by scorpi41** [jonathanlermitage/tikione-jacocoverage#33]
Hi,

if I wan't to change the color theme over options-> JaCoCoverage to "Norway Today", he still use the "Netbeans (default)" theme. I use netbeans version 8.1

**Comment by jonathanlermitage** [comment]
Hi,
This is strange.
do you see interesting things in NetBeans logs? (${DEFAULT_USERDIR_ROOT}/8.1/var/log/messages.log)

Can you try to edit or remove the ${DEFAULT_USERDIR_ROOT}/8.1/config/Preferences/fr/tikione/jacocoverage/plugin.properties file? Is the key "JaCoCoverage.Editor.Theme" set to 0 (normal theme) or 1 (dark theme) ?

**Comment by scorpi41** [comment]
Hi,
there are no interesting logs in ${DEFAULT_USERDIR_ROOT}/8.1/var/log/messages.log. I only found that logs for jacoco: 

fr.tikione.jacocoverage.ext/1 [1.5.0.20150122.2116 150826]
fr.tikione.jacoco.lib/1 [0.7.5.20150524.1946 150826]
fr.tikione.jacocoexec.analyzer/1 [1.5.0.20150116.2200 150826]
fr.tikione.jacocoverage.plugin/1 [1.5.2.20150826.2100 150826]

The key "JaCoCoverage.Editor.Theme" is set to 1. After I deleted the file and chose again the dark theme, the file look like the same before I deleted it.

**Comment by jonathanlermitage** [comment]
Is it a clean install of NetBeans 8.& ? Have you imported plugins from a NetBeans installation ?

**Comment by vra5107** [comment]
I have the same problem. Mine is a clean install. I did not have a previous install on this machine. 

The key "JaCoCoverage.Editor.Theme" is set to 1. Here is the errors from my ${DEFAULT_USERDIR_ROOT}/8.1/var/log/messages.log. 

https://gist.github.com/vra5107/f7b14d4d920e0d22bbde7aaf7891d98a
