### ISSUE TITLE
code highlighting not working with 8.0.2

### ISSUE THREAD

**Issue by jrielsky** [jonathanlermitage/tikione-jacocoverage#35]
I am able to run Test with Jacococoverage, I can see the report in the NetBeans output window and also in the browser window, however there is no code highlighting after the run. The project settings show that code highlighting is enabled, and I've checked the messages.log and see no errors and this is what is in the plugin.properties file:

JaCoCoverage.Editor.EnableCodeHighlighting=true
JaCoCoverage.Editor.EnableCodeHighlightingExtended=true
JaCoCoverage.Editor.Theme=0
JaCoCoverage.Html.AutoOpenReport=true
JaCoCoverage.Html.EnableReport=true
JaCoCoverage.JaCoCoWorkfiles.Rule=0
JaCoCoverage.JavaAgent.customJacocoJarPath=/foo/bar/jacocoagent.jar
JaCoCoverage.JavaAgent.useCustomJacocoJar=false
JaCoCoverage.NbConsole.EnableReport=true

Is there something else I have to do to enable code highlighting?

**Comment by jrielsky** [comment]
After working with this a little longer I believe I've stumbled onto an NetBeans limitation.  I have two related projects that share some source code and I think I read somewhere that NetBeans doesn't like that.  The source is shared via a symlink.  The result is that if I run the tests in one project the highlighting only shows up if I open the files from the other project.

**Comment by jonathanlermitage** [comment]
thx!
