### ISSUE TITLE
Incorrect coverage for synchronized blocks

### ISSUE THREAD

**Issue by marcbrouwertue** [jonathanlermitage/tikione-jacocoverage#36]
Unless I'm doing something wrong, I think there might be an issue with the coverage of synchronized blocks. Below I have attached examples of a simple getter. In the first 2 cases the methods coverage is 67% instead of 100%. The last image as an example where the value is returned outside of the synchronized block, yet the coverage is 72% while I'd expect 100%.

Example 1:
![jaco](https://cloud.githubusercontent.com/assets/11163337/16565581/94846a1c-420e-11e6-9b40-18d7b85142a1.PNG)
Example 2:
![jaco2](https://cloud.githubusercontent.com/assets/11163337/16565711/6bc505a4-420f-11e6-8860-e139cfb44a1a.PNG)
Example 3:
![jaco3](https://cloud.githubusercontent.com/assets/11163337/16566037/bd74e3ae-4211-11e6-93d2-194156e813e6.PNG)

**Comment by jonathanlermitage** [comment]
It seems to be a limitation/bug of JaCoCo. You can fill a bug there: https://github.com/jacoco/jacoco/issues

**Comment by marcbrouwertue** [comment]
Thanks, Ill add an issue to JaCoCo. Changing to 0.7.7 instead of the default 0.7.5 did not resolve the issue.
